### ISSUE TITLE
第二次按双引号只显示双引号中的闭合

### ISSUE THREAD

**Issue by ribber** [renmu123/obsidian-auto-pair-chinese-symbol#12]
第一次输入双引号会出现成对的双引号，再次输入双引号只出现了 “ 这个双引号中的闭合
再次输入双引号又会出现成对的双引号，再次输入双引号又只出现了 “ 这个双引号中的闭合
如此循环往复

![image](https://user-images.githubusercontent.com/5986011/120296863-221f7980-c2fb-11eb-9f8b-95f5dff1e7fd.png)

**Comment by renmu123** [comment]
因为我这里匹配是中文上引号，当输入中文上引号后会自动输入下引号。你第二次按引号键，输入的是下引号，所以无法进行匹配。

可以考虑输入下引号的时候，在侧插入一个上引号。

**Comment by ribber** [comment]
有一些麻烦，请问有没有方法始终输入中文上引号呢？设置输入法？

**Comment by renmu123** [comment]
这要看你的输入法是否支持了，但如果你直接这样设置了，你别的环境（如 word）就没办法输入下引号了

**Comment by ribber** [comment]
插件是否可以实现检测输入的是下引号时替换为上引号和下引号一对呢？

**Comment by renmu123** [comment]
安装一下最新版本0.9.5试一下，是否满足需求

**Comment by ribber** [comment]
好像没有问题了，非常感谢
