### ISSUE TITLE
建议添加一个ignore选项设置

### ISSUE THREAD

**Issue by Nshcn** [renmu123/obsidian-auto-pair-chinese-symbol#13]
插件很方便，但是在obsidian中输入的比较多的是两个中括号[[，obsidian支持中文输入下连按两下【【自动转换成[[]]，但是配和这个插件后，会生成的是[[】】，建议作者能优化一下^_^

**Comment by renmu123** [comment]
等我之后闲下来会增加ignore功能，或者对“【【”特别优化一下
