### ISSUE TITLE
【当出现成对符号时，会一起直接进行删除】这个功能好像没有起效

### ISSUE THREAD

**Issue by lethefrost** [renmu123/obsidian-auto-pair-chinese-symbol#15]
安装插件以后，好像无论是删除左侧符号还是右侧符号，都不会连带着删除配对的另一个符号（哪怕它们中间没有内容，是紧连着的比方说 `《》` ），仍然是单个单个删除的。是否存在bug？版本和系统是macOS Big Sur 11.3.1 + obsidian 0.12.4。

另外这个插件好像对backlink不太友好，去年官方支持了连着输入两个`【【`就可以自动转为`[[`并且唤起backlink菜单的功能，如果用上这个插件的话就会变成`[[】】`，如果在菜单里选了一个条目回车以后，因为官方自动补全的`]]`，会变成`[[笔记]]】】`的形式……

希望大大可以对这种情况做一些优化，比如判断输入连续两个`【【`时就不再自动补全右侧`】】`了？

谢谢～辛苦了

**Comment by lethefrost** [comment]
此外好像还有个问题，就是对于`（）《》【】`这些键盘上分别有两个键的符号来说表现还不错，也和半角符号的补全一样顺手。但是对于像引号`“”`或者`‘’`这样、英文里左右侧引号是同一个字符、键盘上只有单个键的符号来说，输入左引号的`“`的时候，本插件会自动补全右引号`”`，但是系统输入法就记住了左引号输入过了一次，于是在下一回按下这个键的时候会生成右引号，而本插件对右引号没有反应，不会给它自动配对。这样一来，每次都会冗余一个右引号，还需要手动删除，这样就比自己手动输入一对还更麻烦了，让这个补全插件起不到应有的作用了。

不太知道该怎么解决……感觉也许可以让输入法再记住输入过一个右引号，这样下次按键时就可以顺利得到一个左引号了，但不知道实现起来困不困难。简单一点解决方法可能可以让这个插件对左右引号一视同仁，都进行匹配，也在右引号前插入一个左引号，然后把光标往前挪一个字符。

另外希望可以对`「」`这个字符加入匹配～

**Comment by renmu123** [comment]
连对删除我等会儿看一下
下个版本你提的问题应该都能解决#12，#13

**Comment by lethefrost** [comment]
> 连对删除我等会儿看一下
> 下个版本你提的问题应该都能解决#12，#13

谢谢！！辛苦了！

**Comment by renmu123** [comment]
安装一下最新版本0.9.5试一下，两个需求和一个bug应该都已经弄完了

**Comment by lethefrost** [comment]
> 安装一下最新版本0.9.5试一下，两个需求和一个bug应该都已经弄完了

试了一下超棒的！现在好多了！！感谢XD
